DSA_TOPICS = [
    # Pattern Printing
    {"topic": "square pattern", "category": "Pattern Printing", "difficulty": "easy"},
    {"topic": "right triangle pattern", "category": "Pattern Printing", "difficulty": "easy"},
    {"topic": "inverted triangle pattern", "category": "Pattern Printing", "difficulty": "easy"},
    {"topic": "pyramid pattern", "category": "Pattern Printing", "difficulty": "easy"},
    {"topic": "diamond pattern", "category": "Pattern Printing", "difficulty": "easy"},
    {"topic": "hollow patterns", "category": "Pattern Printing", "difficulty": "easy"},
    {"topic": "number patterns", "category": "Pattern Printing", "difficulty": "easy"},
    {"topic": "alphabet patterns", "category": "Pattern Printing", "difficulty": "easy"},

    # Arrays - Basic
    {"topic": "find largest element in array", "category": "Arrays", "difficulty": "easy"},
    {"topic": "second largest element in array", "category": "Arrays", "difficulty": "easy"},
    {"topic": "linear search", "category": "Arrays", "difficulty": "easy"},
    {"topic": "remove duplicates from sorted array", "category": "Arrays", "difficulty": "easy"},
    {"topic": "rotate array by k places", "category": "Arrays", "difficulty": "easy"},
    {"topic": "move zeros to end", "category": "Arrays", "difficulty": "easy"},
    {"topic": "find missing number", "category": "Arrays", "difficulty": "easy"},
    {"topic": "maximum consecutive ones", "category": "Arrays", "difficulty": "easy"},
    {"topic": "find number appearing once", "category": "Arrays", "difficulty": "easy"},

    # Arrays - Intermediate
    {"topic": "union of two sorted arrays", "category": "Arrays", "difficulty": "medium"},
    {"topic": "intersection of two arrays", "category": "Arrays", "difficulty": "medium"},
    {"topic": "longest subarray with sum k", "category": "Arrays", "difficulty": "medium"},
    {"topic": "two sum problem", "category": "Arrays", "difficulty": "medium"},
    {"topic": "sort array of 0s 1s and 2s", "category": "Arrays", "difficulty": "medium"},
    {"topic": "Moore's Voting Algorithm", "category": "Arrays", "difficulty": "medium"},
    {"topic": "Kadane's Algorithm", "category": "Arrays", "difficulty": "medium"},
    {"topic": "rearrange elements by sign", "category": "Arrays", "difficulty": "medium"},
    {"topic": "leaders in an array", "category": "Arrays", "difficulty": "medium"},
    {"topic": "best time to buy and sell stock", "category": "Arrays", "difficulty": "medium"},
    {"topic": "next permutation", "category": "Arrays", "difficulty": "medium"},
    {"topic": "longest consecutive sequence", "category": "Arrays", "difficulty": "medium"},

    # Arrays - Matrix
    {"topic": "set matrix zeros", "category": "Arrays", "difficulty": "medium"},
    {"topic": "rotate matrix by 90 degrees", "category": "Arrays", "difficulty": "medium"},
    {"topic": "spiral traversal of matrix", "category": "Arrays", "difficulty": "medium"},

    # Arrays - Advanced
    {"topic": "count subarrays with sum k", "category": "Arrays", "difficulty": "hard"},
    {"topic": "majority element II", "category": "Arrays", "difficulty": "hard"},
    {"topic": "3 sum problem", "category": "Arrays", "difficulty": "hard"},
    {"topic": "4 sum problem", "category": "Arrays", "difficulty": "hard"},
    {"topic": "number of subarrays with XOR k", "category": "Arrays", "difficulty": "hard"},
    {"topic": "merge overlapping intervals", "category": "Arrays", "difficulty": "hard"},
    {"topic": "merge sorted arrays without extra space", "category": "Arrays", "difficulty": "hard"},
    {"topic": "find missing and repeating number", "category": "Arrays", "difficulty": "hard"},
    {"topic": "count inversions in an array", "category": "Arrays", "difficulty": "hard"},
    {"topic": "reverse pairs", "category": "Arrays", "difficulty": "hard"},
    {"topic": "maximum product subarray", "category": "Arrays", "difficulty": "hard"},

    # Sorting
    {"topic": "selection sort", "category": "Sorting", "difficulty": "easy"},
    {"topic": "bubble sort", "category": "Sorting", "difficulty": "easy"},
    {"topic": "insertion sort", "category": "Sorting", "difficulty": "easy"},
    {"topic": "merge sort", "category": "Sorting", "difficulty": "medium"},
    {"topic": "quick sort", "category": "Sorting", "difficulty": "medium"},
    {"topic": "heap sort", "category": "Sorting", "difficulty": "medium"},

    # Binary Search - Basic
    {"topic": "binary search", "category": "Binary Search", "difficulty": "easy"},
    {"topic": "search insert position", "category": "Binary Search", "difficulty": "easy"},
    {"topic": "first and last occurrence binary search", "category": "Binary Search", "difficulty": "easy"},
    {"topic": "count occurrences binary search", "category": "Binary Search", "difficulty": "easy"},
    {"topic": "lower bound and upper bound", "category": "Binary Search", "difficulty": "easy"},
    {"topic": "search in rotated sorted array", "category": "Binary Search", "difficulty": "medium"},
    {"topic": "minimum in rotated sorted array", "category": "Binary Search", "difficulty": "medium"},
    {"topic": "find rotation count", "category": "Binary Search", "difficulty": "medium"},
    {"topic": "single element in sorted array", "category": "Binary Search", "difficulty": "medium"},
    {"topic": "find peak element", "category": "Binary Search", "difficulty": "medium"},

    # Binary Search on Answers
    {"topic": "square root using binary search", "category": "Binary Search", "difficulty": "medium"},
    {"topic": "nth root of an integer binary search", "category": "Binary Search", "difficulty": "medium"},
    {"topic": "Koko eating bananas", "category": "Binary Search", "difficulty": "medium"},
    {"topic": "minimum days to make bouquets", "category": "Binary Search", "difficulty": "medium"},
    {"topic": "smallest divisor given threshold", "category": "Binary Search", "difficulty": "medium"},
    {"topic": "capacity to ship packages within d days", "category": "Binary Search", "difficulty": "medium"},
    {"topic": "kth missing positive number", "category": "Binary Search", "difficulty": "medium"},
    {"topic": "aggressive cows problem", "category": "Binary Search", "difficulty": "hard"},
    {"topic": "allocate books problem", "category": "Binary Search", "difficulty": "hard"},
    {"topic": "painters partition problem", "category": "Binary Search", "difficulty": "hard"},
    {"topic": "split array largest sum", "category": "Binary Search", "difficulty": "hard"},

    # Binary Search on 2D Arrays
    {"topic": "median of two sorted arrays", "category": "Binary Search", "difficulty": "hard"},
    {"topic": "kth element of two sorted arrays", "category": "Binary Search", "difficulty": "hard"},
    {"topic": "row with maximum number of 1s", "category": "Binary Search", "difficulty": "medium"},
    {"topic": "search in 2D matrix", "category": "Binary Search", "difficulty": "medium"},

    # Strings
    {"topic": "reverse string", "category": "Strings", "difficulty": "easy"},
    {"topic": "palindrome check string", "category": "Strings", "difficulty": "easy"},
    {"topic": "roman to integer", "category": "Strings", "difficulty": "easy"},
    {"topic": "integer to roman", "category": "Strings", "difficulty": "easy"},
    {"topic": "longest palindromic substring", "category": "Strings", "difficulty": "medium"},
    {"topic": "KMP algorithm longest prefix suffix", "category": "Strings", "difficulty": "hard"},
    {"topic": "string matching algorithm", "category": "Strings", "difficulty": "hard"},

    # Recursion
    {"topic": "introduction to recursion", "category": "Recursion", "difficulty": "easy"},
    {"topic": "recursion on subsequences", "category": "Recursion", "difficulty": "medium"},
    {"topic": "combination sum 1", "category": "Recursion", "difficulty": "medium"},
    {"topic": "combination sum 2", "category": "Recursion", "difficulty": "medium"},
    {"topic": "subset sum problem", "category": "Recursion", "difficulty": "medium"},
    {"topic": "print all permutations of string", "category": "Recursion", "difficulty": "medium"},
    {"topic": "palindrome partitioning", "category": "Recursion", "difficulty": "hard"},
    {"topic": "kth permutation sequence", "category": "Recursion", "difficulty": "hard"},
    {"topic": "tower of hanoi", "category": "Recursion", "difficulty": "medium"},

    # Backtracking
    {"topic": "N-queens problem", "category": "Backtracking", "difficulty": "hard"},
    {"topic": "sudoku solver", "category": "Backtracking", "difficulty": "hard"},
    {"topic": "M-coloring problem", "category": "Backtracking", "difficulty": "hard"},
    {"topic": "rat in a maze", "category": "Backtracking", "difficulty": "hard"},

    # Linked Lists - Basic
    {"topic": "insertion in linked list", "category": "Linked Lists", "difficulty": "easy"},
    {"topic": "deletion in linked list", "category": "Linked Lists", "difficulty": "easy"},
    {"topic": "reverse a linked list", "category": "Linked Lists", "difficulty": "easy"},
    {"topic": "find middle element of linked list", "category": "Linked Lists", "difficulty": "easy"},
    {"topic": "detect cycle in linked list", "category": "Linked Lists", "difficulty": "medium"},
    {"topic": "length of loop in linked list", "category": "Linked Lists", "difficulty": "medium"},
    {"topic": "starting point of cycle in linked list", "category": "Linked Lists", "difficulty": "medium"},
    {"topic": "delete middle node linked list", "category": "Linked Lists", "difficulty": "medium"},
    {"topic": "remove nth node from end linked list", "category": "Linked Lists", "difficulty": "medium"},
    {"topic": "merge two sorted linked lists", "category": "Linked Lists", "difficulty": "medium"},
    {"topic": "check palindrome linked list", "category": "Linked Lists", "difficulty": "medium"},

    # Linked Lists - Intermediate
    {"topic": "odd even linked list", "category": "Linked Lists", "difficulty": "medium"},
    {"topic": "add two numbers in linked list", "category": "Linked Lists", "difficulty": "medium"},
    {"topic": "intersection point of two linked lists", "category": "Linked Lists", "difficulty": "medium"},
    {"topic": "doubly linked list operations", "category": "Linked Lists", "difficulty": "medium"},

    # Linked Lists - Advanced
    {"topic": "reverse nodes in k-group", "category": "Linked Lists", "difficulty": "hard"},
    {"topic": "flatten linked list", "category": "Linked Lists", "difficulty": "hard"},
    {"topic": "merge k sorted linked lists", "category": "Linked Lists", "difficulty": "hard"},
    {"topic": "clone linked list with random pointers", "category": "Linked Lists", "difficulty": "hard"},

    # Stacks & Queues
    {"topic": "balanced parenthesis stack", "category": "Stacks & Queues", "difficulty": "easy"},
    {"topic": "infix to postfix conversion", "category": "Stacks & Queues", "difficulty": "medium"},
    {"topic": "implement min stack", "category": "Stacks & Queues", "difficulty": "medium"},
    {"topic": "next greater element stack", "category": "Stacks & Queues", "difficulty": "medium"},
    {"topic": "stock span problem", "category": "Stacks & Queues", "difficulty": "medium"},
    {"topic": "trapping rainwater problem", "category": "Stacks & Queues", "difficulty": "hard"},
    {"topic": "sliding window maximum", "category": "Stacks & Queues", "difficulty": "hard"},
    {"topic": "largest rectangle in histogram", "category": "Stacks & Queues", "difficulty": "hard"},
    {"topic": "LRU cache implementation", "category": "Stacks & Queues", "difficulty": "hard"},

    # Binary Trees
    {"topic": "preorder inorder postorder traversal", "category": "Binary Trees", "difficulty": "easy"},
    {"topic": "level order traversal binary tree", "category": "Binary Trees", "difficulty": "easy"},
    {"topic": "maximum depth of binary tree", "category": "Binary Trees", "difficulty": "easy"},
    {"topic": "check balanced binary tree", "category": "Binary Trees", "difficulty": "medium"},
    {"topic": "lowest common ancestor binary tree", "category": "Binary Trees", "difficulty": "medium"},
    {"topic": "diameter of binary tree", "category": "Binary Trees", "difficulty": "medium"},
    {"topic": "maximum path sum binary tree", "category": "Binary Trees", "difficulty": "hard"},
    {"topic": "vertical order traversal binary tree", "category": "Binary Trees", "difficulty": "hard"},
    {"topic": "serialize and deserialize binary tree", "category": "Binary Trees", "difficulty": "hard"},
    {"topic": "Morris traversal binary tree", "category": "Binary Trees", "difficulty": "hard"},

    # BST
    {"topic": "search in BST", "category": "BST", "difficulty": "easy"},
    {"topic": "insert node in BST", "category": "BST", "difficulty": "easy"},
    {"topic": "delete node in BST", "category": "BST", "difficulty": "medium"},
    {"topic": "validate BST", "category": "BST", "difficulty": "medium"},
    {"topic": "LCA in BST", "category": "BST", "difficulty": "medium"},
    {"topic": "kth smallest element in BST", "category": "BST", "difficulty": "medium"},
    {"topic": "BST iterator", "category": "BST", "difficulty": "medium"},
    {"topic": "recover BST with swapped nodes", "category": "BST", "difficulty": "hard"},
    {"topic": "largest BST in binary tree", "category": "BST", "difficulty": "hard"},

    # Heap
    {"topic": "heap build and heap sort", "category": "Heap", "difficulty": "medium"},
    {"topic": "kth largest element heap", "category": "Heap", "difficulty": "medium"},
    {"topic": "kth smallest element heap", "category": "Heap", "difficulty": "medium"},
    {"topic": "median in a stream", "category": "Heap", "difficulty": "hard"},
    {"topic": "merge k sorted arrays heap", "category": "Heap", "difficulty": "hard"},
    {"topic": "smallest range from k lists", "category": "Heap", "difficulty": "hard"},

    # Sliding Window
    {"topic": "longest substring without repeating characters", "category": "Sliding Window", "difficulty": "medium"},
    {"topic": "longest substring with at most k distinct characters", "category": "Sliding Window", "difficulty": "medium"},
    {"topic": "maximum points from cards", "category": "Sliding Window", "difficulty": "medium"},
    {"topic": "longest repeating character replacement", "category": "Sliding Window", "difficulty": "medium"},
    {"topic": "minimum window substring", "category": "Sliding Window", "difficulty": "hard"},
    {"topic": "subarray with k different integers", "category": "Sliding Window", "difficulty": "hard"},

    # Graphs
    {"topic": "BFS traversal graph", "category": "Graphs", "difficulty": "medium"},
    {"topic": "DFS traversal graph", "category": "Graphs", "difficulty": "medium"},
    {"topic": "cycle detection in undirected graph", "category": "Graphs", "difficulty": "medium"},
    {"topic": "cycle detection in directed graph", "category": "Graphs", "difficulty": "medium"},
    {"topic": "topological sort", "category": "Graphs", "difficulty": "medium"},
    {"topic": "bipartite graph check", "category": "Graphs", "difficulty": "medium"},
    {"topic": "flood fill algorithm", "category": "Graphs", "difficulty": "medium"},
    {"topic": "rotten oranges BFS", "category": "Graphs", "difficulty": "medium"},
    {"topic": "word ladder problem", "category": "Graphs", "difficulty": "hard"},
    {"topic": "Dijkstra's Algorithm", "category": "Graphs", "difficulty": "hard"},
    {"topic": "Bellman Ford Algorithm", "category": "Graphs", "difficulty": "hard"},
    {"topic": "Floyd Warshall Algorithm", "category": "Graphs", "difficulty": "hard"},
    {"topic": "Prim's Algorithm minimum spanning tree", "category": "Graphs", "difficulty": "hard"},
    {"topic": "Kruskal's Algorithm minimum spanning tree", "category": "Graphs", "difficulty": "hard"},
    {"topic": "Disjoint Set Union find", "category": "Graphs", "difficulty": "hard"},
    {"topic": "Kosaraju's Algorithm strongly connected components", "category": "Graphs", "difficulty": "hard"},
    {"topic": "Tarjan's Algorithm bridges in graph", "category": "Graphs", "difficulty": "hard"},

    # Dynamic Programming
    {"topic": "memoization vs tabulation DP", "category": "Dynamic Programming", "difficulty": "medium"},
    {"topic": "climbing stairs DP", "category": "Dynamic Programming", "difficulty": "easy"},
    {"topic": "frog jump DP", "category": "Dynamic Programming", "difficulty": "easy"},
    {"topic": "maximum sum of non-adjacent elements", "category": "Dynamic Programming", "difficulty": "medium"},
    {"topic": "house robber problem", "category": "Dynamic Programming", "difficulty": "medium"},
    {"topic": "grid unique paths DP", "category": "Dynamic Programming", "difficulty": "medium"},
    {"topic": "minimum path sum in grid", "category": "Dynamic Programming", "difficulty": "medium"},
    {"topic": "0/1 knapsack problem", "category": "Dynamic Programming", "difficulty": "medium"},
    {"topic": "coin change minimum coins", "category": "Dynamic Programming", "difficulty": "medium"},
    {"topic": "longest common subsequence", "category": "Dynamic Programming", "difficulty": "medium"},
    {"topic": "longest palindromic subsequence", "category": "Dynamic Programming", "difficulty": "medium"},
    {"topic": "edit distance problem", "category": "Dynamic Programming", "difficulty": "hard"},
    {"topic": "wildcard matching DP", "category": "Dynamic Programming", "difficulty": "hard"},
    {"topic": "longest increasing subsequence", "category": "Dynamic Programming", "difficulty": "medium"},
    {"topic": "matrix chain multiplication DP", "category": "Dynamic Programming", "difficulty": "hard"},
    {"topic": "burst balloons DP", "category": "Dynamic Programming", "difficulty": "hard"},
    {"topic": "best time to buy and sell stock DP variants", "category": "Dynamic Programming", "difficulty": "hard"},
    {"topic": "count square submatrices DP", "category": "Dynamic Programming", "difficulty": "medium"},
    {"topic": "word break DP", "category": "Dynamic Programming", "difficulty": "medium"},
    {"topic": "jump game DP", "category": "Dynamic Programming", "difficulty": "medium"},

    # Bit Manipulation
    {"topic": "check odd or even using bits", "category": "Bit Manipulation", "difficulty": "easy"},
    {"topic": "check power of 2 using bits", "category": "Bit Manipulation", "difficulty": "easy"},
    {"topic": "set clear toggle ith bit", "category": "Bit Manipulation", "difficulty": "easy"},
    {"topic": "count set bits", "category": "Bit Manipulation", "difficulty": "easy"},
    {"topic": "single number XOR", "category": "Bit Manipulation", "difficulty": "easy"},
    {"topic": "two unique numbers XOR", "category": "Bit Manipulation", "difficulty": "medium"},
    {"topic": "subsets using bit masking", "category": "Bit Manipulation", "difficulty": "medium"},
]